version: '3'


services:
  db:
    image: postgres:14.11
    restart: always
    ports:
      - "5400:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: deckexcdb
    volumes:
      - ./postgres:/var/lib/postgresql/data